AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

Layout/ExtraSpacing:
  AllowForAlignment: true

RSpec/ExpectChange:
  Enabled: true
  EnforcedStyle: block

RSpec/MultipleExpectations:
  Enabled: false
