version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
            # Once lower-level offenses are resolved, the fail-level flags should be removed
      # so that any offense will cause the build to fail.
      - run:
          name: Rubocop
          command: bundle exec rubocop #--fail-level warning --display-only-fail-level-offenses
