version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: cimg/ruby:2.6.7
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Install Bundler
          command: gem install bundler:2.2
      - ruby/bundle-install
      - run:
          name: Rubocop
          # CodeClimate will also run Rubocop, but only on PRs.
          # Running Rubocop in CircleCI allows us to see failures earlier
          command: bundle exec rubocop
      - run:
          name: Build Gem
          # Ensure the gem can be successfully built
          command: bundle exec rake build
